server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**
        - id: invoice
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/invoices/**
        - id: auth
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/auth/**

security:
  oauth2:
    resourceserver:
      jwt:
        public-key-location: classpath:certs/public-key.pem

rsa:
  public-key: classpath:certs/public-key.pem

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
